/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ExemplosRouteImport } from './routes/exemplos'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as EmpresaDashboardRouteImport } from './routes/empresa.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosRoute = ExemplosRouteImport.update({
  id: '/exemplos',
  path: '/exemplos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaDashboardRoute = EmpresaDashboardRouteImport.update({
  id: '/empresa/dashboard',
  path: '/empresa/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  ExemplosRoute: typeof ExemplosRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  PlanosRoute: typeof PlanosRoute
  SobreRoute: typeof SobreRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmpresaDashboardRoute: typeof EmpresaDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos': {
      id: '/exemplos'
      path: '/exemplos'
      fullPath: '/exemplos'
      preLoaderRoute: typeof ExemplosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/dashboard': {
      id: '/empresa/dashboard'
      path: '/empresa/dashboard'
      fullPath: '/empresa/dashboard'
      preLoaderRoute: typeof EmpresaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  ExemplosRoute: ExemplosRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  PlanosRoute: PlanosRoute,
  SobreRoute: SobreRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmpresaDashboardRoute: EmpresaDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
